# Generated by Django 4.1 on 2023-11-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DocOrgnizer", "0003_userprofile_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
