# Generated by Django 4.2.7 on 2023-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOrgnizer', '0005_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
