# Generated by Django 4.2.7 on 2023-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOrgnizer', '0009_remove_userprofile_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
