# Generated by Django 5.0.1 on 2024-01-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DocOrgnizer", "0012_loginattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginAttempt",
        ),
    ]
