# Generated by Django 5.0.1 on 2024-01-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DocOrgnizer", "0014_loginattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="national_id_photo",
        ),
    ]
