# Generated by Django 4.1 on 2023-12-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user_profile",
        ),
    ]
